# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/client.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/client.proto\x12\x0f\x63lientconnector\"z\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\x12\x13\n\x0blast_active\x18\x05 \x01(\x03\x12\x15\n\rmetadata_json\x18\x06 \x01(\t\"R\n\x14\x43reateSessionRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\"\x1f\n\x11GetSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x13\x43loseSessionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x43loseSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x13ListSessionsRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\"B\n\x14ListSessionsResponse\x12*\n\x08sessions\x18\x01 \x03(\x0b\x32\x18.clientconnector.Session2\xf0\x02\n\x0eSessionService\x12R\n\rCreateSession\x12%.clientconnector.CreateSessionRequest\x1a\x18.clientconnector.Session\"\x00\x12L\n\nGetSession\x12\".clientconnector.GetSessionRequest\x1a\x18.clientconnector.Session\"\x00\x12]\n\x0c\x43loseSession\x12$.clientconnector.CloseSessionRequest\x1a%.clientconnector.CloseSessionResponse\"\x00\x12]\n\x0cListSessions\x12$.clientconnector.ListSessionsRequest\x1a%.clientconnector.ListSessionsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SESSION']._serialized_start=39
  _globals['_SESSION']._serialized_end=161
  _globals['_CREATESESSIONREQUEST']._serialized_start=163
  _globals['_CREATESESSIONREQUEST']._serialized_end=245
  _globals['_GETSESSIONREQUEST']._serialized_start=247
  _globals['_GETSESSIONREQUEST']._serialized_end=278
  _globals['_CLOSESESSIONREQUEST']._serialized_start=280
  _globals['_CLOSESESSIONREQUEST']._serialized_end=313
  _globals['_CLOSESESSIONRESPONSE']._serialized_start=315
  _globals['_CLOSESESSIONRESPONSE']._serialized_end=354
  _globals['_LISTSESSIONSREQUEST']._serialized_start=356
  _globals['_LISTSESSIONSREQUEST']._serialized_end=396
  _globals['_LISTSESSIONSRESPONSE']._serialized_start=398
  _globals['_LISTSESSIONSRESPONSE']._serialized_end=464
  _globals['_SESSIONSERVICE']._serialized_start=467
  _globals['_SESSIONSERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
