# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import client_pb2 as proto_dot_client__pb2


class SessionServiceStub(object):
    """The SessionService provides an administrative gRPC API for managing active
    agent sessions within the Client Connector.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/clientconnector.SessionService/CreateSession',
                request_serializer=proto_dot_client__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_client__pb2.Session.FromString,
                )
        self.GetSession = channel.unary_unary(
                '/clientconnector.SessionService/GetSession',
                request_serializer=proto_dot_client__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=proto_dot_client__pb2.Session.FromString,
                )
        self.CloseSession = channel.unary_unary(
                '/clientconnector.SessionService/CloseSession',
                request_serializer=proto_dot_client__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=proto_dot_client__pb2.CloseSessionResponse.FromString,
                )
        self.ListSessions = channel.unary_unary(
                '/clientconnector.SessionService/ListSessions',
                request_serializer=proto_dot_client__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_client__pb2.ListSessionsResponse.FromString,
                )


class SessionServiceServicer(object):
    """The SessionService provides an administrative gRPC API for managing active
    agent sessions within the Client Connector.
    """

    def CreateSession(self, request, context):
        """Create a new session record.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Retrieve an existing session by its ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Mark a session as closed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List all active sessions, optionally filtered by tenant_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=proto_dot_client__pb2.CreateSessionRequest.FromString,
                    response_serializer=proto_dot_client__pb2.Session.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=proto_dot_client__pb2.GetSessionRequest.FromString,
                    response_serializer=proto_dot_client__pb2.Session.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=proto_dot_client__pb2.CloseSessionRequest.FromString,
                    response_serializer=proto_dot_client__pb2.CloseSessionResponse.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=proto_dot_client__pb2.ListSessionsRequest.FromString,
                    response_serializer=proto_dot_client__pb2.ListSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clientconnector.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """The SessionService provides an administrative gRPC API for managing active
    agent sessions within the Client Connector.
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientconnector.SessionService/CreateSession',
            proto_dot_client__pb2.CreateSessionRequest.SerializeToString,
            proto_dot_client__pb2.Session.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientconnector.SessionService/GetSession',
            proto_dot_client__pb2.GetSessionRequest.SerializeToString,
            proto_dot_client__pb2.Session.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientconnector.SessionService/CloseSession',
            proto_dot_client__pb2.CloseSessionRequest.SerializeToString,
            proto_dot_client__pb2.CloseSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientconnector.SessionService/ListSessions',
            proto_dot_client__pb2.ListSessionsRequest.SerializeToString,
            proto_dot_client__pb2.ListSessionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
